# Generated by Django 4.2 on 2024-11-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='genre',
            new_name='genres',
        ),
    ]
