# Generated by Django 4.2 on 2024-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_rename_genre_play_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='show_time',
            field=models.DateTimeField(),
        ),
    ]
