# Generated by Django 4.2 on 2024-11-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_alter_performance_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatre.performance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservaion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatre.reservation'),
        ),
    ]
