# Generated by Django 4.2 on 2024-11-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_alter_ticket_performance_alter_ticket_reservaion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='reservaion',
            new_name='reservation',
        ),
    ]
