# Generated by Django 5.1.3 on 2024-11-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_rename_reservaion_ticket_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='performance',
            field=models.ManyToManyField(blank=True, related_name='props', to='theatre.performance'),
        ),
    ]
